# Generated by Django 5.2.6 on 2025-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='news_views',
            new_name='product_views',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
