# Generated by Django 5.2.5 on 2025-10-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sepatu Running', 'Sepatu Running'), ('Jersey', 'Jersey'), ('Sepatu Futsal', 'Sepatu Futsal'), ('Topi', 'Topi'), ('Sepatu Bola', 'Sepatu Bola'), ('Celana Training', 'Celana Trainings')], default='update', max_length=40),
        ),
    ]
